version: '3'
services:
  botpress:
    image: botpress/server:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data:/botpress/data
    environment:
      - BPFS_STORAGE=database
      - DATABASE_URL=postgres://user:pass@host:5432/dbname  # Replace with your DB details if using external Postgres
